project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
files:
  - source: /lang/lang_zh_CN.properties
    translation: /lang/lang_%language%.properties
    languages_mapping:
      language:
        zh-TW: zh_TW
        en: en
